language: java
jdk:
  - openjdk11



cache:
  directories:
  - "$HOME/.m2"

addons:
  sonarcloud:
    organization: "chiacchius"
    token:
      secure: "LhI3qtG1nG30Yj+W28KGF00UMjGsd3HTdfyKTDTaCpcCFCm1RZLXa+7juLZGnGwWhK3Pkb3racfxhhf2Y73tuTEao+0Z4dmB39xwcFHpjuE03WTU/fj4VSoXWIOcX/uS28sBIAgfvA0AV15PVJZTkh8spMUp1xcLRFw7qlhIAZr9Dku3FWMUJnnPSfOPOO0jI4ns8tRrJSIVMWCmOyTO+4TgLR15FjgCjNIdai1Xxt2cAEuUKZKmbdFJEPTWYoygbQ/GXmWG++yxNtfkWHz9KpLfWR6NbNrkWX71I1b34ri0LSE7pvi9qDRsEiW6mFvw75YFdZtBucapkJQzaF4PJ5augrZF7i9rYvav/zU8Gno3GKvSB9hiRdC/lwXZOdGkzL+NXywKoNmd+wRIWSy18RYSNsrJNMTAdUxFYLVkxiEAm2BxIJVQVQEbEKQ3xuOgsrmUB8WeaoC6PSsxf2ecoDd1Bc7Ef9+w6ljJiIeIj2OUhaLV2OE3P2FgCzM7OKFO4M7zq2VJDmOyOOmOyBD1v0zPCJHBcizeppHRII6cG2XS3K5Hz3RYKtP0f4XEiyjDle37nW6hieuUC+RI9z1bes/GwIx9yUqKPLfsUG5r6d9e8nOoqqEtbYJcIkkX2LXZtiBLz4KQAPrzRBdMFig+d5pTJU+ngh3TztC8hLb3S+4=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=chiacchius_zookeeper2
#install: mvn clean install -DskipTests=true
#script: mvn clean apache-rat:check install -DskipTests spotbugs:check checkstyle:check -Pfull-build
#script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify

branches:
  only:
  - master
  - branch-3.5
  - branch-3.4
