language: java
jdk:
  - openjdk11




cache:
  directories:
  - "$HOME/.m2"

addons:
  sonarcloud:
    organization: "chiacchius"
    token:
      secure: "U0IZ7dIPTQCHQgFfBCWNwjxtutu2zBkIJ99Wbr6lOahBocwYwSAQED5lYFb1ADThnUpdnbBIClT+ClmWzNEB/Y8qbfKKQwQ39ZYJAD/ZyxGWZcMcwWt3LJlhCTATWvuFomVB9vvlubxGTX8cVKuwkaQdYqpx05a0dkuADoFZcmtTGr8JwuxwSu6stPbq+NAyd9Ddpp4t+GPFDtqi9q8DkEWU6I1jM6N+llITI/NKvz6QFfGMCHuXqITTTXhCPfdGhm79t5g/wz4pcxGIfvwvMoQaHMWfwfuvxFXii+ExeJ3gbat+ecZyy5ozqWkZ1Z9zsD2IMDtzolmxvJd8SX16ghxuIeBTBLkNRp97VtF9tUHnp14Mn5Z659GggEARpjha9tGX1WbY0ehHr1A+lFGuwCK+evfbG9KLqv11xntNWfN4akYbi7Bc39f1CThhZiefqD/Rf5bqnnd3nXjNDAtUz60PbKrF2r3iVg8ylsoc0wEQRv0YYFrljUkNEdLbxHiQkxVDk0Vn56mzFZnrDjNZDBA8i/0/G2GL1QUw1PX6rbXuaGXd0PLtakHk2SAtdUsgvZ1QfxPOlftq1p06chV/DExiZRBaYUeCxGVEyW08VuYEtOrZ3QCCJUrR5WnJQkgu0NE66dUgG1gga1vp9kPzQeqzfSeSFrM8E4l2v5JSXJA=" # encrypted value of your token

script:
 
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.login=da0e008f121f5c655169c42021afb37858a9f1a5

branches:
  only:
  - master
  - branch-3.5
  - branch-3.4
